version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - media:/app/media
      - static:/app/static
  
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      # - ../frontend/:/app/result_build/
      - static:/app/result_build/build/
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/


  # gateway:
  #   image: sfgronk/foodgram_gateway
  #   env_file: .env
  #   ports:
  #     - 10000:80
  #   volumes:
  #     - static:/usr/share/nginx/html/
  #     - media:/usr/share/nginx/html/media/